services:
  web:
    build: .
    command: >
      sh -c "
        apt-get update &&
        apt-get install -y netcat-openbsd &&
        while ! nc -z db 5432; do sleep 1; done &&
        python manage.py migrate --noinput &&
        gunicorn cryptdrive.wsgi:application --bind 0.0.0.0:8000
      "
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cryptdrive/static:/cryptdrive/static:ro
      - ./cryptdrive/media:/cryptdrive/media:ro
    depends_on:
      - web

volumes:
  postgres_data:
